name: references_doc_issue
description: Action for referencesDocIssue
inputs:
  comment:
    description: Input for comment
runs:
  using: composite
  steps:
  - shell: bash
    run: npm i @shopware-ag/gh-project-automation
  - name: Run referencesDocIssue
    uses: actions/github-script@5c56fde4671bc2d3592fb0f2c5b5bab9ddae03b1
    env:
      COMMENT: ${{ inputs.comment }}
    with:
      script: |-
        const { referencesDocIssue } = await import('${{ github.workspace }}/node_modules/@shopware-ag/gh-project-automation/dist/index.mjs');
        await referencesDocIssue({github, core, context, fetch}, JSON.parse(process.env.COMMENT));
