name: has_doc_issue_comment
description: Action for hasDocIssueComment
inputs:
  issue_id:
    description: Input for issueId
runs:
  using: composite
  steps:
  - shell: bash
    run: npm i @shopware-ag/gh-project-automation
  - name: Run hasDocIssueComment
    uses: actions/github-script@5c56fde4671bc2d3592fb0f2c5b5bab9ddae03b1
    env:
      ISSUE_ID: ${{ inputs.issue_id }}
    with:
      script: |-
        const { hasDocIssueComment } = await import('${{ github.workspace }}/node_modules/@shopware-ag/gh-project-automation/dist/index.mjs');
        await hasDocIssueComment({github, core, context, fetch}, process.env.ISSUE_ID);
