issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/gh-project-automation:.*
claim_pattern:
  workflow_ref: shopware/gh-project-automation/.github/workflows/release.yml@refs/heads/trunk

permissions:
  contents: write
  pull_requests: write
