name: Check repositories for missing license
on:
  schedule:
    - cron: "* 7 * * *"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  check-mossing-repository-license:
    name: Check repositories of missing license
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: octo-sts/action@v1.0.0
        id: octo-sts
        with:
          scope: shopware
          identity: MissingRepositoryLicenseCheck
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - uses: actions/github-script@v7
        with:
          github-token: ${{ steps.octo-sts.outputs.token }}
          script: |
            const { checkMissingLiceneInRepos } = await import('${{github.workspace}}/dist/index.mjs');
            await checkMissingLiceneInRepos({github, core, context}, "shopware");

