on:
  push:
    branches:
      - main
name: release-please

permissions:
  id-token: write
  contents: read

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
        id: sts-release
        with:
          scope: shopware/gh-project-automation
          identity: release
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          release-type: node
          token: ${{ steps.sts-release.outputs.token }}
      # The logic below handles the npm publication:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 20
          # this is requried for publishing the package correctly! https://stackoverflow.com/a/77539464
          registry-url: "https://registry.npmjs.org"
        if: ${{ steps.release.outputs.release_created }}
      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest
        if: ${{ steps.release.outputs.release_created }}
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      # authentication happens automatically via OIDC. See https://www.npmjs.com/package/@shopware-ag/gh-project-automation/access
      - run: npm publish
        if: ${{ steps.release.outputs.release_created }}
