on:
  push:
    branches:
      - main
name: release-please

permissions:
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: octo-sts/action@v1.0.0
        id: sts-release
        with:
          scope: shopware/gh-project-automation
          identity: release
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          token: ${{ steps.sts-release.outputs.token }}
      # The logic below handles the npm publication:
      - uses: actions/checkout@v4
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
        if: ${{ steps.release.outputs.release_created }}
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
